### ISSUE TITLE
Ошибка при зуммировании

### ISSUE THREAD

**Issue by rom-ger** [asborisov/ya-pdf-viewer#5]
Привет. Столкнулся с такой проблемой. При зуммировании документа все элементы документа становятся невидимыми, а в консоль валится ошибка 
Uncaught (in promise) Error: Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.
    at InternalRenderTask_initializeGraphics [as initializeGraphics] (api.js:2286)
    at api.js:948
    at <anonymous>

с чем это может быть связано?

**Comment by asborisov** [comment]
Привет. Есть идея что при зуме происходит частые ререндеры и рассинхрон событий.
Например: идёт отрисовка, в этот момент происходит зум. Начинается новая отрисовка без отмены старой. Вываливается ошибка. 

Можешь показать как используется либа или, ещё лучше, создать проект где можно воспроизвести ошибку?

**Comment by rom-ger** [comment]
если можешь, напиши мне в телеграм пожалуйста +79098413973 , подробнее покажу всё
